# Generated by Django 4.2.7 on 2023-12-04 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 12, 4, 0, 25, 43, 175568)),
        ),
    ]
